name: animated_toggle
description: Animated Toggle Give you easy way to make your custom Animated toggle.
version: 0.0.8
homepage: https://github.com/LoayOmar/Animated_Toggle

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  decimal: ^2.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dartdoc: ^6.3.0

flutter: